version: '3.9'

services:
  # API Gateway
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8000" # Exposed to the world
    networks:
      - auth_network
      - message_network

  # Authentication Service
  auth-service:
    build:
      context: ./auth-service
    environment:
      DATABASE_URL: postgres://auth_user:auth_password@auth-db:5432/auth_db
    depends_on:
      - auth-db
    networks:
      - auth_network

  auth-db:
    image: postgres:15
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - auth_network

  # Messaging Service
  message-service:
    build:
      context: ./message-service
    environment:
      MONGO_URL: mongodb://message-db:27017
    depends_on:
      - message-db
    networks:
      - message_network

  message-db:
    image: mongo:latest
    volumes:
      - message_data:/data
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - message_network

volumes:
  auth_data:
  message_data:

networks:
  auth_network:
  message_network:
